### ISSUE TITLE
Plugin Question

### ISSUE THREAD

**Issue by Silas888** [leehendricks/homebridge-rachio-platform#1]
So first off great plugin. It definitely works but I have a few variations as to what is shown.  First when I select a zone and go to settings, I only have two options listed for my default run time: 5 minutes and 10 minutes. Your diagram shows more selections, at least up to 30 minutes in 5 minute increments. How do I get a bigger selection?

Secondly, on my Homekit Favorites screen, I can not hide the Rachio controller icon. Normally with other icons, turning off the "Include in favorites" toggle will do it but that toggle is not an option with this icon.

**Comment by efthymakis** [comment]
Echo the comments above.  This is much more stable than the native HomeKit support Rachio 3 provides.

If we can expose longer run times and hide the Rachio Controller from the favorites tab, that'd be great.

**Comment by efthymakis** [comment]
I did some digging and can see where in the code the Controller is added as an accessory.  I can't figure out how, but I believe registering the device with some additional characteristics may solve the problem -- like is done with the zones.  I can see the Rachio Controller in the Home App and in HomeKit extended apps like 'Controller for HomeKit' with no device type defined .  It does not appear in 'Eve for HomeKit', for instance, since there is nothing to trigger off of.

Since zones are part of the Controller accessory, the parent Controller cannot be deleted.  However, if a characteristic displayed as a switch is added to the device, then I suspect the favorites flag will also appear.  Perhaps a switch defining ON/STANDBY is appropriate?  I'll try to dig into any Rachio web hook documentation to see if they expose those actions to even consider it.

**Comment by efthymakis** [comment]
Perhaps these calls will work:
ON.                     /public/device/on   (Turn ON all features of the device (schedules, weather intelligence, water budget, etc.))
STANDBY.          /public/device/off.  (Turn OFF all features of the device (schedules, weather intelligence, water budget, etc.))

**Comment by black01gt** [comment]
@efthymakis  where you able to get this to work?

**Comment by efthymakis** [comment]
@black01gt unfortunately,i don't have any scripting experience to code a solution.  I'm hoping @leehendricks might be able to take some of my comments and translate them into a solution.
